<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Service;
use App\Models\TeamMember;
use App\Models\Property;
use App\Models\Inquiry;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Create Default Administrator
        User::firstOrCreate(
            ['email' => 'admin@nnajioacompany.com'],
            [
                'name' => 'Principal Administrator',
                'password' => Hash::make('AdminNnaji2026!'),
                'email_verified_at' => now(),
            ]
        );

        // 2. Seed Services
        $services = [
            [
                'title' => 'Property & Asset Valuation',
                'slug' => 'property-valuation',
                'icon' => 'fa-calculator',
                'subtitle' => '₦50B+ in Certified Asset Valuations across Nigeria',
                'short_description' => 'Comprehensive statutory and commercial valuation for Land, Buildings, Industrial Plants, Machinery, Oil & Gas facilities, and Agricultural Investments.',
                'full_description' => 'NNAJI O.A & COMPANY undertakes valuation of properties and tangible assets throughout Nigeria in accordance with NIESV standards and ESVRBON regulations. Our valuation practice covers diverse purposes including Mortgage Financing, Insurance, Balance Sheet Auditing, Mergers & Acquisitions, Privatization, Capital Gains, Property Rating, and Compulsory Acquisition Compensation.',
                'scope_of_work' => [
                    'Mortgage & Bank Collateral Valuation',
                    'Insurance Replacement Cost Appraisals',
                    'Balance Sheet & Auditing Statement of Affairs',
                    'Compulsory Acquisition & Compensation for Infrastructure (Pipelines, Roads, Transmission Lines)',
                    'Mergers, Takeovers, and Corporate Splitting-Up',
                    'Plant, Machinery, Oil Tanks & Heavy Industrial Equipment Coding & Valuation',
                    'Agricultural & Agro-Allied Farm Land & Livestock Valuations',
                ],
                'asset_classes' => [
                    'Commercial High-Rises & Office Complexes',
                    'Industrial Plants, Breweries & Manufacturing Facilities',
                    'Oil & Gas Tank Farms, Rigs & Marine Assets',
                    'Residential Estates & Luxury Developments',
                    'Agricultural Farmlands & Processing Mills',
                    'Heavy Machinery, Vehicles & Equipment Inventories',
                ],
                'featured_image' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
                'sort_order' => 1,
            ],
            [
                'title' => 'Property & Facility Management',
                'slug' => 'property-management',
                'icon' => 'fa-building-shield',
                'subtitle' => 'Over 100 Properties Managed | ₦3.3B+ Asset Portfolio',
                'short_description' => 'End-to-end management of commercial office towers, residential estates, retail centers, and institutional facilities maximizing net operating income.',
                'full_description' => 'Our Property and Facility Management Division handles high-value properties across Kaduna, Abuja, Lagos, and Abia. We ensure optimal capital preservation, high occupancy rates, proactive maintenance schedules, lease administration, and strict financial accounting.',
                'scope_of_work' => [
                    'Building Structure & External Works Maintenance',
                    'Tenant Vetting, Lease Administration & Rental Collection',
                    'Mechanical, Electrical & Technical Systems Maintenance',
                    'Security, Fire Safety & Access Control Management',
                    'Space Planning & Optimization for Corporate Occupiers',
                    'Preparation of Annual Service Charge Budgets & Audited Statements',
                ],
                'asset_classes' => [
                    'Multi-Storey Corporate Office Towers',
                    'Gated Residential Communities & Apartments',
                    'Commercial Shopping Malls & Plazas',
                    'Student Hostels & Educational Campuses',
                ],
                'featured_image' => 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
                'sort_order' => 2,
            ],
            [
                'title' => 'Estate Agency & Brokerage',
                'slug' => 'estate-agency',
                'icon' => 'fa-handshake',
                'subtitle' => 'High-Integrity Acquisitions, Sales & Corporate Lettings',
                'short_description' => 'Strategic advisory and brokerage for acquisition, sale, and corporate letting of prime real estate assets nationwide.',
                'full_description' => 'Our Estate Agency department matches qualified buyers and institutional tenants with premium property owners. We conduct rigorous due diligence, title verification, commercial marketing, structured lease negotiations, and legal handing-over documentation.',
                'scope_of_work' => [
                    'Targeted Multi-Channel Marketing & Disposals',
                    'Institutional Land & Commercial Acquisition Advisory',
                    'Price & Lease Terms Negotiation',
                    'Title Verification & Legal Documentation Coordination',
                    'Comprehensive Schedule of Condition & Inventory Handing-Over',
                ],
                'asset_classes' => [
                    'Prime Commercial Plots & Development Sites',
                    'Luxury Residential Villas & Penthouses',
                    'Industrial Warehouses & Logistics Hubs',
                    'Retail Spaces & Mixed-Use Plazas',
                ],
                'featured_image' => 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80',
                'sort_order' => 3,
            ],
            [
                'title' => 'Investment Appraisal & Project Management',
                'slug' => 'investment-appraisal',
                'icon' => 'fa-chart-pie',
                'subtitle' => 'Feasibility Studies for ₦5B+ Cumulative Capital Projects',
                'short_description' => 'Rigorous viability analyses, financial modeling, sensitivity testing, and development project management to guarantee optimal ROI.',
                'full_description' => 'We assist banks, private equity firms, consortiums, and institutional investors in evaluating real estate developments. From initial market demand analysis and cash flow forecasting to full project management oversight, we protect capital and minimize construction delays and wastages.',
                'scope_of_work' => [
                    'Comprehensive Feasibility & Viability Studies',
                    'Market Demand & Supply Dynamics Analysis',
                    'Cash Flow Forecasts, Projected P&L & Balance Sheet Modeling',
                    'Sensitivity Testing, Risk Analysis & Mitigation Strategies',
                    'Full Life-Cycle Project Management Oversight',
                    'Consortium Financing & Site/Services Scheme Advisory',
                ],
                'asset_classes' => [
                    'Residential Estate Masterplans & Gated Communities',
                    'Hospitality & Hotel Developments',
                    'Agro-Allied Processing Complexes',
                    'Commercial Retail & Logistics Parks',
                ],
                'featured_image' => 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80',
                'sort_order' => 4,
            ],
            [
                'title' => 'Revenue Strategy & Corporate Turnaround',
                'slug' => 'revenue-strategy',
                'icon' => 'fa-arrows-rotate',
                'subtitle' => 'Maximizing Yields & Distressed Asset Restructuring',
                'short_description' => 'Proprietary restructuring methodologies for underperforming real estate portfolios, mid-market companies, and government entities.',
                'full_description' => 'We diagnose underperforming real estate portfolios and implement strategic restructuring plans that accelerate revenue growth, resolve distressed debt encumbrances, and enhance asset liquidation or refinancing value.',
                'scope_of_work' => [
                    'Revenue Engine & Portfolio Yield Assessment',
                    'Distressed Asset Repositioning & Restructuring',
                    'Private Equity Due Diligence & Upside Evaluation',
                    'Alternative Real Estate Finance Models (Sale-Leaseback, Equity Release)',
                ],
                'asset_classes' => [
                    'Underperforming Corporate Portfolios',
                    'Privatization Candidate Assets',
                    'Bank Collateral Recovery Portfolios',
                ],
                'featured_image' => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80',
                'sort_order' => 5,
            ],
        ];

        foreach ($services as $serviceData) {
            Service::updateOrCreate(['slug' => $serviceData['slug']], $serviceData);
        }

        // 3. Seed Team Members (Real Profiles Extracted from Firm Records)
        TeamMember::query()->delete();

        $teamMembers = [
            [
                'name' => 'ESV Nnaji Nnamdi Ikechukwu',
                'slug' => 'esv-nnaji-nnamdi-ikechukwu',
                'designation' => 'Principal Partner & Head of Practice',
                'cadre' => 'Fellow (FNIVS)',
                'registration_no' => 'FL1143',
                'qualifications' => 'B.Tech (Estate Mgt, FUT Minna 2002), FNIVS, RSV',
                'experience_years' => '20+ Years',
                'branch_location' => 'Abuja Practice Desk (Block 07, Drive 1, Prince and Princess Estate)',
                'phone' => '08037002395, 08187666130',
                'email' => 'nnajioacompany@gmail.com',
                'bio' => "ESV Nnaji Nnamdi Ikechukwu (FL1143) is the Principal Partner and Head of Practice of NNAJI O.A & COMPANY, directing the firm's national practice and strategic expansion while honoring the four-decade foundation established by his late father, Chief Ogwuegbu Agomoh Nnaji.\n\nA Fellow of the Nigerian Institution of Estate Surveyors and Valuers (FNIVS) and registered with ESVRBON, he has spearheaded landmark statutory and commercial asset valuation mandates across Nigeria for AMCON, NDPHC, NNPC, Federal Government Landed Properties Commissions of Inquiry, and the Federal Ministry of Power, Works & Housing.\n\nAccolades: Recipient of the prestigious Award of Excellence by the Estate Management Student Association (EMSA), Abia State Polytechnic.",
                'education' => [
                    ['school' => 'Federal University of Technology, Minna', 'degree' => 'B.Tech (Estate Management)', 'year' => '2002'],
                    ['school' => 'Abia State Polytechnic', 'degree' => 'Award of Excellence by EMSA', 'year' => 'Honour'],
                    ['school' => 'Federal Government College, Kaduna', 'degree' => 'SSCE / WAEC', 'year' => '1994'],
                ],
                'career_history' => [
                    ['role' => 'Principal Partner & Head of Practice', 'company' => 'Nnaji O.A & Company', 'period' => 'Present'],
                    ['role' => 'Managing / Senior Partner', 'company' => 'Nnaji O.A & Company (Abuja)', 'period' => '2005 - 2024'],
                    ['role' => 'Valuation Team Lead', 'company' => 'AMCON & FCTA Landed Properties Review', 'period' => '2012 - Date'],
                ],
                'key_projects' => [
                    'Award of Excellence by Estate Management Student Association (EMSA), Abia State Polytechnic',
                    'Asset Valuation of Integrated Oil & Gas Limited (Tank Farm)',
                    'Asset Valuation of Bendel Feeds and Flour Mills Limited',
                    'Valuation of African First Publishers, Awka',
                    'Ibafon Oil Tank Farm (Calabar Free Trade Zone)',
                    'Coordinating Consultant on 2nd Niger Bridge Access Road Claimants',
                ],
                'special_skills' => [
                    'Practice Leadership & Corporate Strategy',
                    'Commercial Plant & Machinery Valuation',
                    'Oil & Gas Terminal Appraisals',
                    'Property Portfolio Optimization',
                    'Real Estate Finance & Turnaround Models',
                ],
                'avatar' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
                'is_partner' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Chief Ogwuegbu Agomoh Nnaji',
                'slug' => 'chief-o-a-nnaji',
                'designation' => 'Founding Principal Partner & Chief Consultant (In Memoriam)',
                'cadre' => 'Founding Fellow (FNIVS)',
                'registration_no' => 'F231 / A231',
                'qualifications' => 'B.Sc (Hons) Estate Mgt (UNN 1974), Dip (Agric Umudike 1965), FNIVS, RSV',
                'experience_years' => '40+ Years Legacy',
                'branch_location' => 'Kaduna (Founding Head Office)',
                'phone' => '08037002395, 08187666130',
                'email' => 'nnajioacompany@gmail.com',
                'bio' => "The late Chief Ogwuegbu Agomoh Nnaji (FNIVS, RSV) was the founding Principal Partner and Chief Consultant who established NNAJI O.A & COMPANY in 1981. A distinguished Fellow of the Nigerian Institution of Estate Surveyors and Valuers (FNIVS since 1987) and Registered Surveyor and Valuer (RSV since 1978), he served as Branch Manager at Knight Frank & Rutley (Kaduna & Kano), Head of Estate Division at N.N.D.C. (Properties), Past Chairman of NIESV Kaduna State Branch (1984-1989), and Member of the NIESV National Governing Council.\n\nHis pioneering stewardship, strict adherence to professional ethics, and uncompromising standards created an enduring institutional heritage that continues to inspire the firm under the leadership of his son, ESV Nnaji Nnamdi Ikechukwu.",
                'education' => [
                    ['school' => 'University of Nigeria, Nsukka (UNN)', 'degree' => 'B.Sc (Hons) Estate Management (2nd Class Upper)', 'year' => '1971 - 1974'],
                    ['school' => 'School of Agriculture, Umudike Umuahia', 'degree' => 'Diploma in Tropical Agriculture', 'year' => '1964 - 1965'],
                ],
                'career_history' => [
                    ['role' => 'Founding Principal Consultant', 'company' => 'Nnaji O.A. & Company', 'period' => '1981 - 2024'],
                    ['role' => 'Property Manager & Head of Estate Division', 'company' => 'New Nigeria Development Company (N.N.D.C. Ltd)', 'period' => '1978 - 1980'],
                    ['role' => 'Branch Manager', 'company' => 'Knight Frank & Rutley (Nig.) Kaduna', 'period' => '1977 - 1978'],
                    ['role' => 'Estate Surveyor & Valuer (Kano)', 'company' => 'Knight Frank & Rutley (Nig.) Kano', 'period' => '1975 - 1976'],
                    ['role' => 'Pupil Land Officer', 'company' => 'Enterprises Promotion Board Lagos (Fed. Min. of Trade & Industry)', 'period' => '1974 - 1975'],
                    ['role' => 'Asst. Agricultural Superintendent (Seconded to USAID Team)', 'company' => 'Eastern Nigerian Public Service', 'period' => '1966 - 1969'],
                ],
                'key_projects' => [
                    'Valuation of Durbar Hotel Limited, Kaduna',
                    'Valuation of Jafco Industries Limited & Drinko Industries Ltd',
                    'Assessment and Payment of Compensation for Kano State Urban Development Board',
                    'Coordinating Consultancy for Compensation along Owerri-Egbema-Omoku & Enugu-Ikot Ekpene Transmission Lines',
                    'Valuations for AMCON nationwide and Federal Government Landed Properties Commission of Inquiry',
                ],
                'special_skills' => [
                    'Foundational Practice Standards',
                    'High-Stakes Asset Valuation',
                    'Statutory Land Acquisition & Compensation',
                    'Arbitration & Expert Witness',
                ],
                'avatar' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
                'is_partner' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'ESV Sabe Terungwa',
                'slug' => 'esv-sabe-terungwa',
                'designation' => 'Senior Estate Surveyor & Valuer / Associate Partner',
                'cadre' => 'Associate (ANIVS)',
                'registration_no' => 'A3236',
                'qualifications' => 'B.Tech (ATBU Bauchi 2006), M.Sc Facility Mgt (ABU Zaria in-view), ANIVS, RSV',
                'experience_years' => '6+ Years',
                'branch_location' => 'Abuja Regional Office (Prince & Princess Estate)',
                'phone' => '08037002395, 08187666130',
                'email' => 'sabeter@gmail.com',
                'bio' => 'ESV Sabe Terungwa is an accomplished Senior Estate Surveyor & Valuer leading major industrial, corporate valuation, and facility management assignments across the FCT and North-Central regions.',
                'education' => [
                    ['school' => 'Ahmadu Bello University Zaria', 'degree' => 'Masters in Facility Management', 'year' => 'In-View'],
                    ['school' => 'Abubakar Tafawa Balewa University Bauchi', 'degree' => 'B.Tech Estate Management', 'year' => '2006'],
                ],
                'career_history' => [
                    ['role' => 'Senior Estate Surveyor & Valuer', 'company' => 'Nnaji O.A & Company (Abuja)', 'period' => '2015 - Present'],
                    ['role' => 'Resident Estate Surveyor & Valuer', 'company' => 'Jide Taiwo & Co.', 'period' => '2009 - 2015'],
                ],
                'key_projects' => [
                    'Valuation of Assorted Foods & Beverages Ltd for AMCON',
                    'Valuation of Nnana Jacobs & Brothers Ltd, Aba for AMCON',
                    'Integrated Oil and Gas Lagos Valuation',
                    'Benue State Government Industries Privatization Valuations',
                ],
                'special_skills' => ['Facility Operations', 'Viability Studies', 'Industrial Asset Registers'],
                'avatar' => '/storage/team/esv-sabe-terungwa.webp',
                'is_partner' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'ESV Alh. Salisu Muhammad Yahaya Pai',
                'slug' => 'esv-salisu-muhammad-yahaya-pai',
                'designation' => 'Associate Partner',
                'cadre' => 'Associate (ANIVS)',
                'registration_no' => 'A2494',
                'qualifications' => 'HND (Estate Mgt, Kaduna Poly 2000), ANIVS, RSV',
                'experience_years' => '14+ Years',
                'branch_location' => 'Kaduna / Northern Region',
                'phone' => '08037002395, 08187666130',
                'email' => 'info@nnajioacompany.com',
                'bio' => 'ESV Alh. Salisu Muhammad Yahaya Pai is an Associate Partner with extensive valuation and land acquisition experience across Northern and Central Nigeria. He served as Branch Secretary of NIESV Kaduna State Branch and has coordinated valuation of major industrial plants, hotels, steel manufacturing facilities, and oil rigs.',
                'education' => [
                    ['school' => 'Kaduna Polytechnic, Kaduna', 'degree' => 'Higher National Diploma (Estate Management)', 'year' => '2000'],
                    ['school' => 'Kaduna Polytechnic, Kaduna', 'degree' => 'National Diploma (Estate Management)', 'year' => '1997'],
                ],
                'career_history' => [
                    ['role' => 'Associate Partner', 'company' => 'Nnaji O.A & Company', 'period' => '2007 - Present'],
                    ['role' => 'Branch Secretary', 'company' => 'NIESV Kaduna State Branch', 'period' => '2010 - 2014'],
                ],
                'key_projects' => [
                    'Valuation of Bougainvilla Hotels, Port Harcourt (AMCON)',
                    'Valuation of Sparkwest Steel Industries, Lagos',
                    'Index Petrolube Mainstreet-Africa Ltd Assets',
                    'Flotsome Investment Limited (Dredgers & Marine Equipment)',
                    'D.W.C Drilling Limited (Land Oil Rigs Valuation)',
                ],
                'special_skills' => [
                    'Heavy Machinery & Drilling Rig Valuations',
                    'Public Sector Land Acquisition',
                    'Municipal Property Rating',
                ],
                'avatar' => '/storage/team/esv-salisu-pai.webp',
                'is_partner' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Fakaa Tersoo Matthew',
                'slug' => 'fakaa-tersoo-matthew',
                'designation' => 'Resident Surveyor',
                'cadre' => 'Estate Surveyor (M07808, A.7206)',
                'registration_no' => 'M07808 / A.7206',
                'qualifications' => 'M.Tech & B.Tech Estate Management & Valuation (ATBU Bauchi)',
                'experience_years' => '4+ Years',
                'branch_location' => 'Abuja Regional Office (Block 07, Drive 1, Prince and Princess Estate)',
                'phone' => '+2349062171188, +2348072043889',
                'email' => 'takaamatthew@gmail.com',
                'bio' => "FAKAA TERSOO MATTHEW\nAngwan Siyawa, Off Abuja Electricity Distribution Company Kabusa, FCT Abuja.\nContact: +2349062171188, +2348072043889 | Email: takaamatthew@gmail.com\n\nOBJECTIVE: To diligently, innovatively and creatively meet set goals in an organisation based on academic and professional training and experience in line with global best practice, to carve a niche for an organisation by making things differently, giving it an edge over competitors, to imbibe team spirit in order to create a conducive work environment which enhances efficiency and productivity.\n\nCOMPETENCIES:\n• Training professionals on professional application\n• Valuation of assets of all categories\n• Academic and professional research\n• Assisting in the supervision of academic research\n• Information and communication technology (ICT) skills\n• Facility management\n• Property management\n• Project management\n• Real estate agency",
                'education' => [
                    ['school' => 'Abubakar Tafawa Balewa University Bauchi', 'degree' => 'M.Tech Estate Management & Valuation', 'year' => 'Postgraduate'],
                    ['school' => 'Abubakar Tafawa Balewa University Bauchi', 'degree' => 'B.Tech Estate Management', 'year' => 'Graduate'],
                ],
                'career_history' => [
                    ['role' => 'Resident Surveyor', 'company' => 'Nnaji O.A. & Company (Estate Surveyors & Valuers)', 'period' => 'January 2023 - Present'],
                    ['role' => 'Resident Surveyor 1', 'company' => 'Kunle Olaniyan & Partners (Chartered Estate Surveyors & Valuers)', 'period' => 'June 2022 - November 2022'],
                ],
                'key_projects' => [
                    'Valuation of assets of all categories for Asset Management Corporation of Nigeria (AMCON)',
                    'Valuation of assets for National Institute for Legislative and Democratic Studies (NILDS) Abuja',
                    'Management of all categories of properties for clients within and outside Abuja',
                    'Training of Estate Surveyors and Valuers on the application of Estate Surveying',
                    'Preparation of candidates for NIESV Professional Qualifying Examination (PQE) and Professional Practice Examination (PPE)',
                    'Valuation of a block of 4 units 2-bedroom flat at Hillside Estate, Karu Site, FCT Abuja and disposal of same',
                    'Valuation of a 3-bedroom bungalow and 4-bedroom bungalow at House 2, Cooperative Avenue, Dafara Area, Kuje, Abuja',
                    'Valuation of a parcel of land at Road 3 Phase 4, Nyanya, Abuja',
                ],
                'special_skills' => [
                    'AMCON & NILDS Asset Valuations',
                    'Facility & Property Management',
                    'NIESV PQE & PPE Candidate Training',
                    'ICT & Valuation Research',
                ],
                'avatar' => 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
                'is_partner' => false,
                'sort_order' => 5,
            ],
            [
                'name' => 'ESV Ikenna Nmezu Onwumere',
                'slug' => 'ikenna-nmezu-onwumere',
                'designation' => 'Branch Head / Estate Surveyor',
                'cadre' => 'Probationer (G06267)',
                'registration_no' => 'G06267',
                'qualifications' => 'B.Tech Estate Management (FUT Minna 2006), Cert Deutsch (Goethe)',
                'experience_years' => '5+ Years',
                'branch_location' => 'Abia State Branch (Umuahia)',
                'phone' => '08037002395, 08187666130',
                'email' => 'ikenna_nmezu@yahoo.com',
                'bio' => 'Ikenna Onwumere leads the Abia State Branch operations. Prior to his current post, he held relationship and mortgage credit advisory roles at Fidelity Bank Plc and ASO Savings & Loans Plc.',
                'education' => [
                    ['school' => 'Federal University of Technology Minna', 'degree' => 'B.Tech Estate Management', 'year' => '2000 - 2006'],
                ],
                'career_history' => [
                    ['role' => 'Branch Head / Surveyor', 'company' => 'Nnaji O.A & Company (Abia / Abuja)', 'period' => '2015 - Present'],
                    ['role' => 'Retail Relationship Manager', 'company' => 'Fidelity Bank Plc', 'period' => '2013 - 2014'],
                    ['role' => 'Credit / Mortgage Consultant', 'company' => 'ASO Savings and Loans Plc (Port Harcourt)', 'period' => '2008 - 2012'],
                ],
                'key_projects' => [
                    'Mortgage valuations for Keystone Bank Plc customers',
                    '₦200M construction finance facility for Yenagoa Gardens Estate, Bayelsa',
                    'Second Niger Bridge Access Road compensation claimant surveys',
                ],
                'special_skills' => ['Mortgage Finance', 'Client Advisory', 'Alternative Real Estate Financing'],
                'avatar' => 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&q=80',
                'is_partner' => false,
                'sort_order' => 6,
            ],
            [
                'name' => 'Mrs. Chidi Nnaji',
                'slug' => 'mrs-chidi-nnaji',
                'designation' => 'Diaspora Link Representative (USA)',
                'cadre' => 'International Affiliate',
                'registration_no' => 'USA-DET-01',
                'qualifications' => 'HND (Estate Mgt), PGD, MBA (Management)',
                'experience_years' => '12+ Years',
                'branch_location' => 'Detroit, Michigan, USA',
                'phone' => '+1 (313) 555-0194',
                'email' => 'usa@nnajioacompany.com',
                'bio' => 'Mrs. Chidi Nnaji coordinates real estate investment advisory, diaspora asset valuation inquiries, and cross-border investor services based in Detroit, Michigan.',
                'education' => [
                    ['school' => 'Wayne State University / Regional Program', 'degree' => 'MBA Management', 'year' => '2011'],
                ],
                'career_history' => [
                    ['role' => 'USA Link Director', 'company' => 'Nnaji O.A & Company', 'period' => '2012 - Present'],
                ],
                'key_projects' => [
                    'Diaspora Investment Acquisitions in Abuja & Lagos',
                    'Cross-Border Asset Verification for North American Clients',
                ],
                'special_skills' => ['Diaspora Investment', 'International Client Relations'],
                'avatar' => '/storage/team/mrs-chidi-nnaji.webp',
                'is_partner' => false,
                'sort_order' => 7,
            ],
        ];

        foreach ($teamMembers as $teamData) {
            TeamMember::create($teamData);
        }

        // 4. Seed Properties (Active Listings & Closed Deals for Property Lifecycle Automation)
        $properties = [
            // --- ACTIVE LISTINGS ---
            [
                'title' => 'PRICE SLASHED FOR IMMEDIATE PURCHASE: 3-Floor Office Complex (36 Suites), Zone 1 Wuse',
                'slug' => 'price-slashed-3-floor-office-complex-36-suites-zone-1-wuse',
                'reference_no' => 'NOA-WUS-001',
                'property_type' => 'Commercial',
                'listing_type' => 'for_sale',
                'price' => 3200000000.00,
                'price_prefix' => '₦',
                'price_unit' => 'net',
                'location_address' => 'Zone 1, Wuse District',
                'location_city' => 'Wuse Zone 1, Abuja',
                'location_state' => 'Abuja FCT',
                'bedrooms' => null,
                'bathrooms' => 36,
                'land_area' => 'Ample Commercial Grounds',
                'building_area' => '3-Floor Complex (36 Suites)',
                'description' => "PRICE SLASHED FOR IMMEDIATE PURCHASE.\n\nAn executive commercial office complex developed on 3 floors comprising 36 self-contained suites located in the prestigious Zone 1, Wuse, Abuja.\n\nTITLE: Certificate of Occupancy (C of O).\n\nFURTHER DESCRIPTION & HIGHLIGHTS:\n• Good ambiance with serene commercial prestige\n• Highly accessible location with seamless dual-carriage arterial road linkages\n• High profile and secure neighborhood\n• Generously paved grounds on interlocking stones\n• Dedicated high-capacity transformer guaranteeing uninterrupted power\n• 36 spacious office suites suited for corporate headquarters, diplomatic missions, financial institutions, or premier rental yield.",
                'features' => [
                    'Certificate of Occupancy (C of O)',
                    '3-Floor Commercial Complex (36 Suites)',
                    'Dedicated High-Capacity Transformer',
                    'Well Paved on Interlocking Stones',
                    'Highly Accessible Prime Corridor',
                    'High Profile Neighborhood',
                    'Good Ambiance',
                    'Price Slashed for Immediate Purchase',
                ],
                'featured_image' => '/storage/properties/wuse-zone1-office-complex.webp',
                'gallery_images' => [
                    '/storage/properties/wuse-zone1-office-complex.webp',
                ],
                'status' => 'available', // ACTIVE
                'sold_price' => null,
                'sold_date' => null,
                'client_name' => null,
                'transaction_summary' => null,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'title' => 'Prime 6-Storey Commercial Office Complex, Jabi District',
                'slug' => 'prime-6-storey-commercial-office-complex-jabi',
                'reference_no' => 'NOA-ABJ-001',
                'property_type' => 'Commercial',
                'listing_type' => 'for_sale',
                'price' => 1850000000.00,
                'price_prefix' => '₦',
                'price_unit' => 'total',
                'location_address' => 'Off I.T. Igbani Street, Jabi District',
                'location_city' => 'Jabi, Abuja',
                'location_state' => 'Abuja FCT',
                'bedrooms' => null,
                'bathrooms' => 18,
                'land_area' => '2,850 sqm',
                'building_area' => '4,200 sqm Usable Space',
                'description' => 'A state-of-the-art commercial high-rise situated in the heart of Jabi business corridor. Features high-speed passenger elevators, dedicated 500kVA soundproof generator, 80-car paved parking apron, central HVAC conduits, borehole water reticulation with industrial filtration, and full C of O.',
                'features' => [
                    'C of O (Certificate of Occupancy)',
                    '500kVA Soundproof Generator',
                    '2 High-Speed Kone Elevators',
                    '80-Car Secure Paved Parking',
                    '24/7 CCTV & Security Post',
                    'Catering Canteen & Rooftop Terrace',
                ],
                'featured_image' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1000&q=80',
                    'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1000&q=80',
                    'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1000&q=80',
                ],
                'status' => 'available', // ACTIVE
                'sold_price' => null,
                'sold_date' => null,
                'client_name' => null,
                'transaction_summary' => null,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'title' => 'Luxury 5-Bedroom Fully Detached Mansion with Swimming Pool',
                'slug' => 'luxury-5-bedroom-fully-detached-mansion-maitama',
                'reference_no' => 'NOA-ABJ-002',
                'property_type' => 'Residential',
                'listing_type' => 'for_sale',
                'price' => 750000000.00,
                'price_prefix' => '₦',
                'price_unit' => 'total',
                'location_address' => 'Gana Street Corridor, Maitama',
                'location_city' => 'Maitama, Abuja',
                'location_state' => 'Abuja FCT',
                'bedrooms' => 5,
                'bathrooms' => 6,
                'land_area' => '1,400 sqm',
                'building_area' => '850 sqm',
                'description' => 'Architectural masterpiece crafted for executive diplomatic or high-net-worth living. Features marble flooring throughout, smart home automation, Olympic-sized swimming pool, 2-bedroom guest chalet, 2-room staff quarters, and bulletproof security doors.',
                'features' => [
                    'Smart Home Automation',
                    'Private Swimming Pool & Gazebo',
                    '2-Bedroom Detached Guest Chalet',
                    'Fitted Italian Kitchen with Granite Islands',
                    'FCDA Certificate of Occupancy',
                    'Automated Perimeter Electric Fence',
                ],
                'featured_image' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
                    'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1000&q=80',
                ],
                'status' => 'available', // ACTIVE
                'sold_price' => null,
                'sold_date' => null,
                'client_name' => null,
                'transaction_summary' => null,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'title' => 'Prime Industrial Warehouse & Logistics Complex, Kakuri',
                'slug' => 'prime-industrial-warehouse-kakuri-kaduna',
                'reference_no' => 'NOA-KAD-003',
                'property_type' => 'Industrial',
                'listing_type' => 'for_lease',
                'price' => 45000000.00,
                'price_prefix' => '₦',
                'price_unit' => 'per annum',
                'location_address' => 'Industrial Layout, Kakuri',
                'location_city' => 'Kaduna South',
                'location_state' => 'Kaduna State',
                'bedrooms' => null,
                'bathrooms' => 8,
                'land_area' => '8,500 sqm',
                'building_area' => '4,000 sqm Bay Height 12m',
                'description' => 'Heavy-duty industrial facility equipped with reinforced concrete flooring, overhead 10-ton gantry crane rails, 3-phase high-voltage power transformer (1MVA), administrative office block, and heavy articulation trailer turning radius.',
                'features' => [
                    '1MVA Dedicated Industrial Transformer',
                    '10-Ton Overhead Crane Mounts',
                    'Trailer Loading Docks & Turnaround Bay',
                    'Administrative 2-Storey Office Annex',
                    'Full Industrial C of O & Fire Compliance',
                ],
                'featured_image' => 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=1000&q=80',
                ],
                'status' => 'available', // ACTIVE
                'sold_price' => null,
                'sold_date' => null,
                'client_name' => null,
                'transaction_summary' => null,
                'is_featured' => false,
                'sort_order' => 3,
            ],
            [
                'title' => 'Commercial Mixed-Use Plaza, Abakpa GRA Corridor',
                'slug' => 'commercial-mixed-use-plaza-abakpa-gra',
                'reference_no' => 'NOA-KAD-004',
                'property_type' => 'Commercial',
                'listing_type' => 'for_sale',
                'price' => 420000000.00,
                'price_prefix' => '₦',
                'price_unit' => 'total',
                'location_address' => 'Yunus Ustaz Usman Road, Abakpa GRA',
                'location_city' => 'Kaduna North',
                'location_state' => 'Kaduna State',
                'bedrooms' => null,
                'bathrooms' => 12,
                'land_area' => '1,800 sqm',
                'building_area' => '2,200 sqm',
                'description' => 'Strategically situated 3-storey commercial property featuring 24 open-plan office suites and banking hall with verified high rental yield history.',
                'features' => [
                    'Direct Arterial Road Frontage',
                    'Banking Hall with Bullion Van Access',
                    '100% Occupancy Track Record',
                    'Kaduna State Registered Title',
                ],
                'featured_image' => 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=1200&q=80',
                'gallery_images' => [],
                'status' => 'available', // ACTIVE
                'sold_price' => null,
                'sold_date' => null,
                'client_name' => null,
                'transaction_summary' => null,
                'is_featured' => true,
                'sort_order' => 4,
            ],
            [
                'title' => '50-Hectare Commercial Agricultural & Agro-Allied Farm Land',
                'slug' => '50-hectare-commercial-agricultural-farm-umuahia',
                'reference_no' => 'NOA-ABI-005',
                'property_type' => 'Agricultural',
                'listing_type' => 'for_sale',
                'price' => 280000000.00,
                'price_prefix' => '₦',
                'price_unit' => 'total',
                'location_address' => 'Umuopara by Abia Tower Expressway',
                'location_city' => 'Umuahia',
                'location_state' => 'Abia State',
                'bedrooms' => null,
                'bathrooms' => null,
                'land_area' => '50 Hectares (123.5 Acres)',
                'building_area' => 'Farm Houses & Processing Mill Sheds',
                'description' => 'Expansive fertile arable land suitable for cassava processing, oil palm plantation, and livestock ranching. Direct expressway access with natural stream boundary.',
                'features' => [
                    'Perimeter Surveyed & Registered Deed of Assignment',
                    'Natural Water Source for Irrigation',
                    'Direct Expressway Frontage for Logistics',
                    'Processing Sheds & Farm Manager Quarters',
                ],
                'featured_image' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
                'gallery_images' => [],
                'status' => 'available', // ACTIVE
                'sold_price' => null,
                'sold_date' => null,
                'client_name' => null,
                'transaction_summary' => null,
                'is_featured' => false,
                'sort_order' => 5,
            ],

            // --- CLOSED DEALS & PORTFOLIO ARCHIVES (Historical Valuations / Disposals from PDF) ---
            [
                'title' => 'Durbar Hotel Limited Commercial & Hospitality Asset Valuation',
                'slug' => 'durbar-hotel-limited-asset-valuation',
                'reference_no' => 'NOA-CL-001',
                'property_type' => 'Hospitality',
                'listing_type' => 'valuation_record',
                'price' => 8500000000.00,
                'price_prefix' => '₦',
                'price_unit' => 'Valuation Volume',
                'location_address' => 'Independence Way / Ahmadu Bello Way',
                'location_city' => 'Kaduna',
                'location_state' => 'Kaduna State',
                'bedrooms' => 320,
                'bathrooms' => 350,
                'land_area' => '12.4 Hectares',
                'building_area' => 'Multi-Tier Tower & Banquet Complex',
                'description' => 'Comprehensive statutory valuation of the landmark Durbar Hotel complex including main multi-tier guest towers, conference halls, industrial laundry facilities, power generating station, and extensive grounds.',
                'features' => [
                    'Statutory Balance Sheet Valuation',
                    'Inventory Coding of Fixed Assets',
                    'Land & Structures Assessment',
                ],
                'featured_image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
                'gallery_images' => [],
                'status' => 'sold', // CLOSED DEAL
                'sold_price' => 8500000000.00,
                'sold_date' => '2019-11-15',
                'client_name' => 'Durbar Hotel Limited / Ministry of Commerce',
                'transaction_summary' => 'Executed complete comprehensive asset valuation and fixed asset register coding totaling over ₦8.5 Billion.',
                'is_featured' => true,
                'sort_order' => 10,
            ],
            [
                'title' => 'Integrated Oil & Gas Limited Petroleum Tank Farm & Marine Jetty',
                'slug' => 'integrated-oil-gas-tank-farm-valuation',
                'reference_no' => 'NOA-CL-002',
                'property_type' => 'Industrial',
                'listing_type' => 'valuation_record',
                'price' => 12000000000.00,
                'price_prefix' => '₦',
                'price_unit' => 'Valuation Volume',
                'location_address' => 'Free Trade Zone Corridor',
                'location_city' => 'Calabar & Lagos Ports',
                'location_state' => 'Cross River / Lagos State',
                'bedrooms' => null,
                'bathrooms' => null,
                'land_area' => '18 Hectares Waterfront',
                'building_area' => 'Storage Tanks & Gantry Loading Bays',
                'description' => 'Valuation of major coastal petroleum storage tank farm facilities, loading gantries, pipeline connections, fire suppression systems, and heavy marine berthing infrastructure for AMCON and corporate financing.',
                'features' => [
                    'Specialized Oil & Gas Tangible Assets Appraisal',
                    'Pipeline & Pumping Station Valuation',
                    'AMCON Resolution Portfolio Advisory',
                ],
                'featured_image' => 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
                'gallery_images' => [],
                'status' => 'sold', // CLOSED DEAL
                'sold_price' => 12000000000.00,
                'sold_date' => '2018-06-20',
                'client_name' => 'Asset Management Corporation of Nigeria (AMCON)',
                'transaction_summary' => 'Comprehensive specialized plant, pipeline and marine terminal valuation executed for AMCON.',
                'is_featured' => true,
                'sort_order' => 11,
            ],
            [
                'title' => 'Bougainville Hotel Asset Valuation & Acquisition Advisory',
                'slug' => 'bougainville-hotel-port-harcourt-valuation',
                'reference_no' => 'NOA-CL-003',
                'property_type' => 'Hospitality',
                'listing_type' => 'valuation_record',
                'price' => 3200000000.00,
                'price_prefix' => '₦',
                'price_unit' => 'Appraised Value',
                'location_address' => 'GRA Phase II',
                'location_city' => 'Port Harcourt',
                'location_state' => 'Rivers State',
                'bedrooms' => 110,
                'bathrooms' => 125,
                'land_area' => '6,200 sqm',
                'building_area' => 'Luxury Hospitality Facility',
                'description' => 'Full asset valuation of hotel real estate, commercial fixtures, swimming pool, banquet halls, and central air systems for AMCON restructuring.',
                'features' => [
                    'Hospitality Going-Concern Valuation',
                    'AMCON Portfolio Assessment',
                    'FFE (Furniture, Fixtures & Equipment) Register',
                ],
                'featured_image' => 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
                'gallery_images' => [],
                'status' => 'sold', // CLOSED DEAL
                'sold_price' => 3200000000.00,
                'sold_date' => '2017-09-12',
                'client_name' => 'Asset Management Corporation of Nigeria (AMCON)',
                'transaction_summary' => 'Full valuation of prime hospitality asset and corporate facility review.',
                'is_featured' => false,
                'sort_order' => 12,
            ],
            [
                'title' => 'Wema Bank Building Complex (Former National Bank) Multi-Storey Tower',
                'slug' => 'wema-bank-building-complex-letting-management',
                'reference_no' => 'NOA-CL-004',
                'property_type' => 'Commercial',
                'listing_type' => 'for_lease',
                'price' => 3300000000.00,
                'price_prefix' => '₦',
                'price_unit' => 'Portfolio Value',
                'location_address' => 'Commercial District',
                'location_city' => 'Kaduna',
                'location_state' => 'Kaduna State',
                'bedrooms' => null,
                'bathrooms' => 32,
                'land_area' => '3,500 sqm',
                'building_area' => '8-Floor Commercial Tower',
                'description' => 'Long-term corporate letting and property management mandate for a landmark 8-storey banking and commercial office complex spanning 2001 to 2020.',
                'features' => [
                    '20-Year Retainer Management',
                    'Full Occupancy Letting to Corporate Tenants',
                    'Lift Overhauls & Facility Maintenance',
                ],
                'featured_image' => 'https://images.unsplash.com/photo-1554469384-e58fac16e23a?auto=format&fit=crop&w=1200&q=80',
                'gallery_images' => [],
                'status' => 'leased', // CLOSED DEAL / LEASED PORTFOLIO
                'sold_price' => 3300000000.00,
                'sold_date' => '2020-12-31',
                'client_name' => 'Wema Bank Plc / National Bank',
                'transaction_summary' => 'Successfully managed and let 8-floor landmark commercial complex with over 95% average occupancy across two decades.',
                'is_featured' => true,
                'sort_order' => 13,
            ],
            [
                'title' => 'Jafco & Drinko Manufacturing Industrial Facilities Valuation',
                'slug' => 'jafco-drinko-industrial-liquidation-valuation',
                'reference_no' => 'NOA-CL-005',
                'property_type' => 'Industrial',
                'listing_type' => 'valuation_record',
                'price' => 4600000000.00,
                'price_prefix' => '₦',
                'price_unit' => 'Valuation Total',
                'location_address' => 'Kudenda Industrial Layout',
                'location_city' => 'Kaduna',
                'location_state' => 'Kaduna State',
                'bedrooms' => null,
                'bathrooms' => null,
                'land_area' => '14 Hectares',
                'building_area' => 'Production Halls & Bottling Lines',
                'description' => 'Comprehensive liquidation and corporate restructuring valuation covering land, industrial warehouses, automated bottling plants, cold rooms, and distribution fleet.',
                'features' => [
                    'Liquidation Statement of Affairs Valuation',
                    'Automated Industrial Machinery Breakdown',
                    'Land & Sub-Station Rating Assessment',
                ],
                'featured_image' => 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=80',
                'gallery_images' => [],
                'status' => 'sold', // CLOSED DEAL
                'sold_price' => 4600000000.00,
                'sold_date' => '2016-04-18',
                'client_name' => 'Liquidators / Drinko & Jafco Industries',
                'transaction_summary' => 'Statutory asset valuation for corporate restructuring and liquidation proceedings.',
                'is_featured' => false,
                'sort_order' => 14,
            ],
        ];

        foreach ($properties as $propData) {
            Property::updateOrCreate(['slug' => $propData['slug']], $propData);
        }

        // 5. Seed Inquiries Sample
        Inquiry::create([
            'type' => 'valuation_request',
            'name' => 'Engr. Donald Adeleke',
            'email' => 'donald.adeleke@energyholdings.ng',
            'phone' => '08023456789',
            'organization' => 'Apex Logistics & Energy Ltd',
            'subject' => 'Statutory Valuation for Tank Farm & Logistics Depots',
            'service_category' => 'Property & Asset Valuation',
            'asset_type' => 'Plant & Machinery / Tank Farm',
            'asset_location' => 'Port Harcourt / Lagos Ports',
            'preferred_branch' => 'Abuja Regional Office',
            'message' => 'We require an urgent certified asset valuation for our petroleum storage tank farm and auxiliary machinery for bank collateral and balance sheet auditing.',
            'status' => 'new',
            'admin_notes' => 'Received from web portal. Assign to ESV Ikechukwu Nnaji for initial inspection proposal.',
        ]);
    }
}
